Repository ynput/ayon-documentation, pull requests merged in 2025-02, with the labels that each got.

#338 Add additional docs for substance designer
  website/docs/addon_substancedesigner_artist.md
  website/docs/assets/substance_designer_custom_template_project_creation.png
  website/docs/assets/substance_designer_project_creation_ayon_setting.png
  website/docs/assets/substance_designer_publish_texture_options.png
Labels: documentation

#335 Add quick clean up for sidebar and old pages
  website/docs/admin_docsexamples.md
  website/docs/admin_settings.md
  website/docs/admin_settings_local.md
  website/docs/admin_webserver_for_webpublisher.md
  website/docs/artist_getting_started.md
  website/docs/artist_work.md
  website/sidebars.js
Labels: type: bug

#322 Initial commit of Premiere Integration
  website/docs/addon_premiere_admin.md
  website/docs/addon_premiere_artist.md
  website/docs/assets/json/Ayon_addons_version.json
  website/docs/assets/premiere/admin/install_ayon_extension.png
  website/docs/assets/premiere/artist/premiere_extension.png
  website/docs/assets/premiere/artist/premiere_workfiles_tool.png
  website/docs/assets/premiere/artist/publisher.png
  website/sidebars.js
  website/src/data/addons/addons.ts
  website/src/data/addons/data/img/premiere-icon.png
  website/src/data/addons/data/premiere.ts
Labels: documentation

#321 320 introduce houdini generic loader hdas with examples for users
  website/docs/addon_houdini_artist_loader_hdas.md
  website/docs/assets/houdini/artist/Expr_random_hda_Material_Loader_v001.hda
  website/docs/assets/houdini/artist/hda_context_options_multishots.gif
  website/docs/assets/houdini/artist/hda_custom_loader.png
  website/docs/assets/houdini/artist/hda_custom_loader_textures.png
  website/docs/assets/houdini/artist/hda_example_1_expressions.png
  website/docs/assets/houdini/artist/hda_expressions_lop.png
  website/docs/assets/houdini/artist/hda_expressions_sop.png
  website/docs/assets/houdini/artist/hda_generic_loader.png
  website/docs/assets/houdini/artist/hda_generic_loader_parameters.png
  website/docs/assets/houdini/artist/hda_load_into_file_parm.gif
  website/docs/assets/houdini/artist/hda_load_shot.png
  website/docs/assets/houdini/artist/hda_load_shot_parameters.png
  website/docs/assets/houdini/artist/hda_load_tool.png
  website/docs/assets/houdini/artist/hda_lop_import.png
  website/docs/assets/houdini/artist/hda_lop_import_parameters.png
  website/docs/assets/houdini/artist/hda_lop_tab_menu.png
  website/docs/assets/houdini/artist/hda_obj_tab_menu.png
  website/docs/assets/houdini/artist/hda_sop_tab_menu.png
  website/sidebars.js
Labels: type: enhancement, addon: Houdini, Artist Docs

#346 Remove deprecated info about LODs
  website/docs/artist_tools_inventory.md
  website/docs/assets/tools/tools_scene_inventory_54.png
Labels: type: maintenance

#298 219 bundle documentation
  website/docs/admin_server_bundles_and_addons.md
  website/docs/assets/server/admin/server_and_addons/addon_settings.png
  website/docs/assets/server/admin/server_and_addons/addons_tab.png
  website/docs/assets/server/admin/server_and_addons/bundle_and_addons.png
  website/docs/assets/server/admin/server_and_addons/bundles_list_1.png
  website/docs/assets/server/admin/server_and_addons/bundles_list_2.png
  website/docs/assets/server/admin/server_and_addons/bundles_tab.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_addon.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_addon_project.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_bundle.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_bundle_button.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_bundle_in_project.png
  website/docs/assets/server/admin/server_and_addons/copy_settings_from_another_setting.png
  website/docs/assets/server/admin/server_and_addons/create_bundle.png
  website/docs/assets/server/admin/server_and_addons/dependency_packages.png
  website/docs/assets/server/admin/server_and_addons/low_level_editor.png
  website/docs/assets/server/admin/server_and_addons/right_click_addon_versions_list.png
  website/docs/assets/server/admin/server_and_addons/right_click_addons_list_1.png
  website/docs/assets/server/admin/server_and_addons/right_click_addons_list_2.png
  website/docs/assets/server/admin/server_and_addons/right_click_bundles_list_1.png
  website/docs/assets/server/admin/server_and_addons/right_click_bundles_list_2.png
  website/docs/assets/server/admin/server_and_addons/right_click_bundles_list_3.png
  website/docs/assets/server/admin/server_and_addons/settings_and_overrides_colorcode.png
  website/docs/assets/server/admin/server_and_addons/settings_filter.gif
  website/sidebars.js
Labels: Server
